// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7RxvNHkU6pVd_OEr6P7jJCmDbJ2mvu_o',
    appId: '1:937411013985:android:2c929f87ac3c70fbb6a920',
    messagingSenderId: '937411013985',
    projectId: 'ticketgeneration-47bfe',
    storageBucket: 'ticketgeneration-47bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCkCcYltwTXzSIoObRA_g23FY84How_f4',
    appId: '1:937411013985:ios:e303fdc784bc1936b6a920',
    messagingSenderId: '937411013985',
    projectId: 'ticketgeneration-47bfe',
    storageBucket: 'ticketgeneration-47bfe.appspot.com',
    androidClientId: '937411013985-c8770mf3c0rr6f2qamqsph58oiffoq76.apps.googleusercontent.com',
    iosClientId: '937411013985-too5oeec18mqlv02m8715dr45j01tdfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sih',
  );
}
